#!/usr/bin/env ruby

require 'br'

# { 
#   :application => 'masta',
#   :deploy_code => true,
#   :repository => "git@github.com:arockwell/masta.git"
# }

deploy = BR::Deploy.new
deploy.config[:application]
deploy.config[:repository]
deploy.config[:release_path]
deploy.config[:shared_path]

deploy.symlink

# TOOD: symlinks
release_path = File.expand_path("../../", __FILE__)
puts "release_path #{release_path.inspect}"
shared_path = "/data/masta/shared"
Dir.glob("#{shared_path}/config/*").each do |path|
  puts path
  filename = File.basename(path)
  system "rm -rf #{release_path}/config/#{filename} && \
          ln -sf #{shared_path}/config/#{filename} #{release_path}/config/#{filename}"
end

puts "install dependencies"
system("ln -sf #{shared_path}/node_modules #{release_path}/node_modules")
system "npm install"
# system "jake install:ruby"
# system "jake build:lib"
# system "bundle"
